1 REM NUMBER GUESSING GAME
2 PRINT "\X93"
5 INPUT "ENTER UPPER LIMIT FOR GUESS ";LI
10 NM = INT(LI*RND(1))+1
15 CN = 0
20 PRINT "OK, I THINK I HAVE A NUMBER":PRINT
30 INPUT "YOUR GUESS?"; GU
35 CN = CN + 1
40 IF GU > NM THEN PRINT "AWWW... SORRY, MY NUMBER IS LOWER": PRINT : GOTO 30
50 IF GU < NM THEN PRINT "OUCH! MY NUMBER IS HIGHER!": PRINT : GOTO 30
60 PRINT "OMG!\XA0HOW DID YOU DO THAT? YOU GOT IT!"
70 PRINT "AND IN ONLY ";CN;"GUESSES!"
90 INPUT "FANCY ANOTHER TRY? (Y/N): ";AN$
95 IF AN$ = "" THEN GOTO 90
100 IF AN$ = "Y" THEN 2
110 IF AN$ <> "N" THEN 90
120 END