1 REM DICE ROLL
5 PRINT "CARE TO TRY YOUR LUCK, HUMAN?"
10 PRINT "RED DICE = "; INT(6*RND(1))+1
20 PRINT "WHITE DICE = "; INT(6*RND(1))+1
30 PRINT "HIT SPACE BAR FOR ANOTHER ROLL. E FOR EXIT":PRINT
40 GET A$: IF A$ = "" THEN 40
50 IF A$ = CHR$(32)THEN 10
60 IF A$ = "E" THEN END
