10 REM MIXING IT UP A LITTLE
20 ?"YOU CAN ALWAYS DO A KIND OF 'CONCAT' BY USING CERTAIN CHARACTERS"
30 ?"FOR EXAMPLE, YOU CAN USE ';' OR ','"
40 ?"THE ';' WILL PRINT THE NEXT INSTRUCTION RIGHT AFTER THE PREVIOUS ONE:"
50 ?"2+2=";2+2
60 ?"HOWEVER, THE ',' WILL SEPARATE THE TEXT INTO COLUMNS"
70 ?"COLUMN 1","COLUMN 2","COLUMN 3"
80 END