1 REM MIXING IT UP A LITTLE
10 PRINT"\X93"
20 PRINT"YOU CAN ALWAYS DO A KIND OF 'CONCAT' BY USING CERTAIN CHARACTERS"
30 PRINT"FOR EXAMPLE, YOU CAN USE ';' OR ','"
40 PRINT"THE ';' WILL PRINT THE NEXT INSTRUCTION RIGHT AFTER THE PREVIOUS ONE:"
50 PRINT"2+2=";2+2
55 PRINT"\X11"
60 PRINT"HOWEVER, THE ',' WILL SEPARATE THE TEXT INTO COLUMNS"
70 PRINT"COLUMN 1","COLUMN 2","COLUMN 3"
80 END