1 REM MIXING IT UP A LITTLE
2 ?"YOU CAN ALWAYS DO A KIND OF 'CONCAT' BY USING CERTAIN CHARACTERS"
3 ?"FOR EXAMPLE, YOU CAN USE ';' OR ','"
4 ?"THE ';' WILL PRINT THE NEXT INSTRUCTION RIGHT AFTER THE PREVIOUS ONE:"
5 ?"2+2=";2+2
6 ?"HOWEVER, THE ',' WILL SEPARATE THE TEXT INTO COLUMNS"
7 ?"COLUMN 1","COLUMN 2","COLUMN 3"
8 END